# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Weather Closet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weather Closet
  pod 'Alamofire'  

  target 'Weather ClosetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Weather ClosetUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
